import asyncio
import base64
import os
from pathlib import Path
from typing import List, Dict, Tuple, Optional, Any # Added Any
from google import genai
from google.genai import types
# Placeholder imports for prompt modules - will create these files later
# import vendor_prompts
# import product_prompts
import tiktoken
import json
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
from dotenv import load_dotenv
import time
import re
import markdown
import yaml
import logging
import signal
import sys
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
from rich.logging import RichHandler
from rich.panel import Panel

# Import PDF generator and config (assuming they exist at root level now)
from pdf_generator import process_markdown_files
from config import VENDOR_SECTION_ORDER, PRODUCT_INITIAL_SECTION_ORDER, PRODUCT_FULL_SECTION_ORDER # Example usage
from config import LLM_MODEL, LLM_TEMPERATURE, OUTPUT_DIR

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(rich_tracebacks=True, show_path=False)] # Hide file paths
)
logger = logging.getLogger("rich")

# Rich console for better output
console = Console()

# Global flag for graceful shutdown
shutdown_requested = False

def signal_handler(signum, frame):
    """Handle interrupt signals gracefully."""
    global shutdown_requested
    if not shutdown_requested:
        console.print("\n[yellow]Shutdown requested. Completing current tasks...[/yellow]")
        shutdown_requested = True
    else:
        console.print("\n[red]Force quitting...[/red]")
        sys.exit(1)

# Register signal handlers in main

# Load environment variables from .env file
load_dotenv()

def count_tokens(text: str) -> int:
    """Count the number of tokens in a text string."""
    try:
        encoding = tiktoken.get_encoding("cl100k_base") # Using OpenAI's encoding
        return len(encoding.encode(text))
    except Exception as e:
        logger.warning(f"Tiktoken counting failed: {e}. Returning character count / 4.")
        return len(text) // 4 # Rough approximation if tiktoken fails

def format_time(seconds: float) -> str:
    """Format time in seconds to a human-readable string."""
    if seconds < 60:
        return f"{seconds:.2f} seconds"
    minutes = int(seconds // 60)
    remaining_seconds = seconds % 60
    if minutes < 60:
        return f"{minutes} minutes {remaining_seconds:.2f} seconds"
    hours = int(minutes // 60)
    remaining_minutes = minutes % 60
    return f"{hours} hours {remaining_minutes} minutes {remaining_seconds:.2f} seconds"

def _generate_single_section(client: genai.Client, prompt: str, output_path: Path) -> Dict:
    """Internal function: Generate content for a single prompt/section."""
    start_time = time.time()
    input_tokens = 0
    output_tokens = 0
    try:
        # Ensure directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        input_tokens = count_tokens(prompt)

        contents = [types.Content(role="user", parts=[types.Part.from_text(text=prompt)])]
        tools = [types.Tool(google_search=types.GoogleSearch())]
        generate_content_config = types.GenerateContentConfig(
            temperature=LLM_TEMPERATURE,
            tools=tools,
            response_mime_type="text/plain",
        )

        response = client.generate_content(
            model=LLM_MODEL,
            contents=contents,
            generation_config=generate_content_config,
            request_options={'timeout': 600} # Increased timeout to 10 minutes
        )

        # Check for blocked content or missing text
        if not response.candidates or not response.candidates[0].content.parts:
             if response.prompt_feedback.block_reason:
                 raise ValueError(f"Content blocked. Reason: {response.prompt_feedback.block_reason.name}. Details: {response.prompt_feedback.safety_ratings}")
             else:
                 raise ValueError("No content generated by the model. Response might be empty.")

        full_output = "".join(part.text for part in response.candidates[0].content.parts if hasattr(part, 'text'))

        if not full_output.strip():
             logger.warning(f"Generated empty content for {output_path.name}. Check prompt or model response.")
             # Consider if this should be an error or just a warning depending on expected behavior

        output_tokens = count_tokens(full_output)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(full_output)

        execution_time = time.time() - start_time
        return {
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "total_tokens": input_tokens + output_tokens,
            "execution_time": execution_time,
            "status": "success"
        }

    except Exception as e:
        execution_time = time.time() - start_time
        logger.error(f"Error generating content for {output_path.name}: {str(e)}")
        # Save error details to the file if possible
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(f"# Generation Error\n\nAn error occurred while generating this section:\n\n```\n{str(e)}\n```")
        except Exception as write_e:
            logger.error(f"Additionally, failed to write error details to {output_path.name}: {write_e}")

        return {
            "input_tokens": input_tokens, # Keep input tokens if prompt was generated
            "output_tokens": 0,
            "total_tokens": input_tokens,
            "execution_time": execution_time,
            "status": "error",
            "error": str(e)
        }

def _generate_report_sections(
    research_mode: str, # 'vendor' or 'product'
    identifier: str, # Vendor name or Product category
    context_company_name: str,
    optional_inputs: Dict[str, Any], # Dict for product_category, certs, region etc.
    section_config: List[Tuple[str, str]], # e.g., VENDOR_SECTION_ORDER
    prompt_module: Any, # The imported module (vendor_prompts or product_prompts)
    progress=None # Rich progress object
    ) -> Tuple[Optional[Dict], Optional[Path]]:
    """
    Core function to generate sections for a given mode (vendor/product).
    This is a placeholder structure to be heavily adapted in later phases.
    """
    start_time = time.time()
    global shutdown_requested

    # Get API key from .env file
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        logger.error("GEMINI_API_KEY not found in .env file")
        return None, None
    try:
        client = genai.Client(api_key=api_key)
    except Exception as e:
        logger.error(f"Failed to initialize Google GenAI Client: {e}")
        return None, None

    # --- Directory Setup ---
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    sanitized_identifier = re.sub(r'[\\/*?:"<>|]', "", identifier) # Sanitize identifier for path
    base_dir_name = f"{research_mode}_{sanitized_identifier}_{timestamp}"
    base_dir = Path(OUTPUT_DIR) / base_dir_name
    base_dir.mkdir(parents=True, exist_ok=True)

    markdown_dir = base_dir / "markdown"
    pdf_dir = base_dir / "pdf"
    misc_dir = base_dir / "misc"
    markdown_dir.mkdir(exist_ok=True)
    pdf_dir.mkdir(exist_ok=True)
    misc_dir.mkdir(exist_ok=True)

    # --- Save Generation Config ---
    config_data = {
        "research_mode": research_mode,
        "identifier": identifier,
        "context_company_name": context_company_name,
        "optional_inputs": optional_inputs,
        "timestamp": datetime.now().isoformat(),
        "sections": [section_id for section_id, _ in section_config],
        "model": LLM_MODEL,
        "temperature": LLM_TEMPERATURE,
    }
    try:
        with open(misc_dir / "generation_config.yaml", "w", encoding='utf-8') as f:
            yaml.dump(config_data, f, allow_unicode=True)
    except Exception as e:
        logger.warning(f"Could not save generation config: {e}")


    # --- Parallel Section Generation ---
    results = {}
    # If no progress display is provided, create a dummy one
    class DummyProgress:
        def add_task(self, *args, **kwargs): return None
        def update(self, *args, **kwargs): pass
    progress = progress or DummyProgress()

    # Create section tasks for progress bar
    section_tasks = {
        section_id: progress.add_task(f"[cyan]{section_id:.<30}", total=1, visible=True)
        for section_id, _ in section_config
    }

    # Determine max workers (adjust as needed based on API limits/performance)
    max_workers = min(len(section_config), 10) # Example limit

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {}
        for section_id, prompt_func_name in section_config:
            if shutdown_requested:
                logger.warning(f"Shutdown requested, skipping section: {section_id}")
                results[section_id] = {"status": "skipped", "error": "Shutdown requested"}
                continue

            try:
                prompt_func = getattr(prompt_module, prompt_func_name)
                # Prepare arguments for prompt function (adapt as needed per prompt)
                prompt_args = {
                    'identifier': identifier, # Pass vendor name or product category
                    'language': "English", # Hardcoded as multi-language is removed
                    'context_company_name': context_company_name,
                    **optional_inputs # Pass optional inputs like certs, region
                }
                # Remove keys not expected by the specific prompt function if necessary
                # (Requires inspecting function signatures - more advanced)

                # Call the appropriate prompt function
                prompt = prompt_func(**prompt_args) # Pass necessary args

                output_path = markdown_dir / f"{section_id}.md"
                future = executor.submit(_generate_single_section, client, prompt, output_path)
                futures[future] = section_id
            except AttributeError:
                 logger.error(f"Prompt function '{prompt_func_name}' not found in module. Skipping.")
                 results[section_id] = {"status": "error", "error": f"Prompt function '{prompt_func_name}' not found."}
                 progress.update(section_tasks[section_id], description=f"[red]{section_id:.<30}✗ (Not Found)", completed=1)
            except Exception as e:
                logger.error(f"Error preparing prompt for {section_id}: {e}")
                results[section_id] = {"status": "error", "error": f"Error preparing prompt: {e}"}
                progress.update(section_tasks[section_id], description=f"[red]{section_id:.<30}✗ (Prompt Error)", completed=1)


        for future in as_completed(futures):
            section_id = futures[future]
            try:
                if not shutdown_requested:
                    result = future.result()
                    results[section_id] = result
                    # Update progress bar
                    status_char = "✓" if result['status'] == 'success' else "✗"
                    color = "green" if result['status'] == 'success' else "red"
                    progress.update(section_tasks[section_id],
                                    advance=1,
                                    description=f"[{color}]{section_id:.<30}{status_char}")
                else:
                    # If shutdown happened while waiting
                    results[section_id] = {"status": "interrupted", "error": "Shutdown requested"}
                    progress.update(section_tasks[section_id], description=f"[yellow]{section_id:.<30}⚠ (Interrupted)")

            except Exception as e:
                logger.error(f"Error getting result for {section_id}: {str(e)}")
                results[section_id] = {"status": "error", "error": str(e)}
                progress.update(section_tasks[section_id], description=f"[red]{section_id:.<30}✗ (Future Error)", completed=1)

    # --- Compile Stats & Save ---
    total_execution_time = time.time() - start_time
    token_stats = {
        "sections": results,
        "summary": {
            "total_input_tokens": sum(r.get("input_tokens", 0) for r in results.values()),
            "total_output_tokens": sum(r.get("output_tokens", 0) for r in results.values()),
            "total_tokens": sum(r.get("total_tokens", 0) for r in results.values()),
            "total_execution_time": total_execution_time,
            "formatted_execution_time": format_time(total_execution_time),
            "timestamp": datetime.now().isoformat(),
            "research_mode": research_mode,
            "identifier": identifier,
            "context_company_name": context_company_name,
            "optional_inputs": optional_inputs,
            "model": LLM_MODEL,
            "temperature": LLM_TEMPERATURE,
            "successful_sections": sum(1 for r in results.values() if r.get("status") == "success"),
            "failed_sections": sum(1 for r in results.values() if r.get("status") not in ["success", "skipped"]),
            "skipped_sections": sum(1 for r in results.values() if r.get("status") == "skipped"),
            "interrupted": shutdown_requested
        }
    }

    try:
        stats_path = misc_dir / "generation_summary.json"
        with open(stats_path, 'w', encoding='utf-8') as f:
            json.dump(token_stats, f, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.warning(f"Could not save generation summary JSON: {e}")

    return token_stats, base_dir

# --- Main Execution Logic (Simplified Placeholder) ---
def run_vendor_research(vendor_name: str, context_company_name: str, optional_inputs: Dict):
    """Placeholder function to run vendor research."""
    console.print(f"\n[bold blue]Starting Vendor Research for: {vendor_name}[/bold blue]")
    # In Phase 1: Import vendor_prompts and use VENDOR_SECTION_ORDER
    # result, base_dir = _generate_report_sections(
    #     research_mode='vendor',
    #     identifier=vendor_name,
    #     context_company_name=context_company_name,
    #     optional_inputs=optional_inputs,
    #     section_config=VENDOR_SECTION_ORDER, # From config
    #     prompt_module=vendor_prompts # Imported module
    # )
    # --- Mock response for Phase 0 ---
    logger.info("Vendor research execution placeholder.")
    mock_base_dir = Path(OUTPUT_DIR) / f"vendor_{vendor_name}_placeholder"
    mock_base_dir.mkdir(parents=True, exist_ok=True)
    (mock_base_dir / "markdown").mkdir(exist_ok=True)
    (mock_base_dir / "pdf").mkdir(exist_ok=True)
    (mock_base_dir / "misc").mkdir(exist_ok=True)
    result = {"summary": {"successful_sections": 0, "failed_sections": 0, "total_execution_time": 0.1}}
    base_dir = mock_base_dir
    # --- End Mock ---

    if result:
        console.print(Panel.fit(
            f"Vendor Research for '{vendor_name}' completed.\n"
            f"Time: {format_time(result['summary']['total_execution_time'])}\n"
            f"Successful Sections: [green]{result['summary']['successful_sections']}[/]\n"
            f"Failed Sections: [red]{result['summary']['failed_sections']}[/]\n"
            f"Output Dir: {base_dir}",
            title="Vendor Research Complete", border_style="blue"
        ))
        # Add PDF generation call here in Phase 1 if successful sections > 0
        # pdf_path = process_markdown_files(base_dir, vendor_name, "VendorReport", section_order=VENDOR_SECTION_ORDER) # Pass section order
    else:
        console.print(f"[red]Vendor Research for {vendor_name} failed.[/red]")

def run_product_research(product_category: str, context_company_name: str, optional_inputs: Dict):
    """Placeholder function to run product research."""
    console.print(f"\n[bold magenta]Starting Product Research for: {product_category}[/bold magenta]")
    # Complex logic for Phase 2 onwards (initial analysis, interaction, filtering, profiles)
    logger.info("Product research execution placeholder.")
    # --- Mock response for Phase 0 ---
    mock_base_dir = Path(OUTPUT_DIR) / f"product_{product_category}_placeholder"
    mock_base_dir.mkdir(parents=True, exist_ok=True)
    (mock_base_dir / "markdown").mkdir(exist_ok=True)
    (mock_base_dir / "pdf").mkdir(exist_ok=True)
    (mock_base_dir / "misc").mkdir(exist_ok=True)
    result = {"summary": {"successful_sections": 0, "failed_sections": 0, "total_execution_time": 0.1}}
    base_dir = mock_base_dir
    # --- End Mock ---

    console.print(Panel.fit(
        f"Product Research for '{product_category}' (placeholder) completed.\n"
        f"Output Dir: {base_dir}",
        title="Product Research Complete", border_style="magenta"
    ))

def main_cli():
    """Basic CLI interaction for testing (will be replaced by Streamlit app)."""
    console.print(Panel.fit("[bold]Vendor & Product Research Agent (CLI Runner)[/bold]", border_style="yellow"))

    mode = console.input("Select mode ([1] Vendor / [2] Product): ")

    if mode == '1':
        vendor_name = console.input("Enter Vendor Name: ")
        context_company = console.input("Enter Your Company Name (Context): ")
        prod_cat = console.input("Optional: Product Category from Vendor: ")
        certs = console.input("Optional: Required Certifications (comma-sep): ")
        region = console.input("Optional: Geographic Region: ")
        optional_inputs = {
            "product_category": prod_cat or None,
            "required_certs": certs or None,
            "region": region or None,
        }
        run_vendor_research(vendor_name, context_company, optional_inputs)
    elif mode == '2':
        product_category = console.input("Enter Product Category: ")
        context_company = console.input("Enter Your Company Name (Context): ")
        certs = console.input("Optional: Required Certifications (comma-sep): ")
        region = console.input("Optional: Geographic Region: ")
        optional_inputs = {
            "required_certs": certs or None,
            "region": region or None,
        }
        run_product_research(product_category, context_company, optional_inputs)
    else:
        console.print("[red]Invalid mode selected.[/red]")


if __name__ == "__main__":
    # Register signal handlers
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    try:
        # Basic CLI runner for now
        main_cli()
    except KeyboardInterrupt:
        console.print("\n[yellow]Process interrupted by user.[/yellow]")
    except Exception as e:
        console.print(f"\n[bold red]An unexpected error occurred:[/]")
        logger.exception(e) # Log the full traceback